const express = require('express');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const db = require('../db');
const { requireAuth, businessIdOf } = require('../auth/middleware');

const router = express.Router();
router.use(requireAuth);

// ============================================================================
// "Amafagitire" (Invoices / Receipts) - gukora PDF y'ifagitire ku bakiriya,
// hakurikijwe amakuru y'igurisha (cyangwa amagurisha yose y'umukiriya umwe).
//
// ICYITONDERWA: iyi fagitire ni inyandiko y'ubucuruzi (internal business
// receipt) ikozwe na sisitemu yacu - NTABWO ari "EBM receipt" yemewe na RRA
// (Electronic Billing Machine ni sisitemu yihariye ya RRA isaba icyemezo
// cyihariye). Iyi fagitire ifasha mu gukurikirana no guha umukiriya
// inyemezabuguzi, ariko ntisimbura EBM niba ubucuruzwa bugomba kuyikoresha.
// ============================================================================

const NAVY = rgb(0.12, 0.16, 0.27);
const ACCENT = rgb(0.545, 0.227, 0.122);
const MUTED = rgb(0.42, 0.42, 0.42);
const LINE = rgb(0.85, 0.83, 0.78);
const WHITE = rgb(1, 1, 1);

function fmtMoney(n) {
  return Math.round(n || 0).toLocaleString('en-US') + ' RWF';
}
function fmtD(iso) {
  if (!iso) return '—';
  const d = new Date(iso);
  return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

async function buildInvoicePdf({ business, invoiceLabel, invoiceNo, date, customer, rows, totals, paymentMethod, businessProfile }) {
  const doc = await PDFDocument.create();
  let page = doc.addPage([595.28, 841.89]); // A4
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  const margin = 46;

  // ---- Header bar ----
  page.drawRectangle({ x: 0, y: height - 108, width, height: 108, color: NAVY });
  page.drawText((businessProfile.businessName || business.name || 'ITTP').toUpperCase(), {
    x: margin, y: height - 52, size: 20, font: bold, color: WHITE
  });
  const subLines = [];
  if (businessProfile.businessAddress) subLines.push(businessProfile.businessAddress);
  if (business.phone) subLines.push(business.phone);
  if (business.email) subLines.push(business.email);
  if (businessProfile.tinNumber) subLines.push('TIN: ' + businessProfile.tinNumber);
  page.drawText(subLines.join('   ·   '), { x: margin, y: height - 72, size: 9.5, font, color: rgb(0.82, 0.84, 0.9) });

  const titleSize = invoiceLabel.length > 22 ? 12.5 : 16;
  const titleW = bold.widthOfTextAtSize(invoiceLabel, titleSize);
  page.drawText(invoiceLabel, { x: width - margin - titleW, y: height - 46, size: titleSize, font: bold, color: WHITE });
  const noText = `No: ${invoiceNo}`;
  page.drawText(noText, { x: width - margin - font.widthOfTextAtSize(noText, 10), y: height - 64, size: 10, font, color: rgb(0.82, 0.84, 0.9) });
  const dateText = `${fmtD(date)}`;
  page.drawText(dateText, { x: width - margin - font.widthOfTextAtSize(dateText, 10), y: height - 78, size: 10, font, color: rgb(0.82, 0.84, 0.9) });

  let y = height - 140;

  // ---- Bill To block ----
  page.drawText('BILL TO / KURI', { x: margin, y, size: 9, font: bold, color: ACCENT });
  y -= 16;
  page.drawText(customer.name || '—', { x: margin, y, size: 13, font: bold, color: NAVY });
  y -= 16;
  const custLine = [customer.phone, customer.email].filter(Boolean).join('   ·   ');
  if (custLine) { page.drawText(custLine, { x: margin, y, size: 10, font, color: MUTED }); y -= 14; }

  y -= 10;
  page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 1, color: LINE });
  y -= 22;

  // ---- Table ----
  const col = { desc: margin, qty: 330, price: 400, total: 480 };
  const drawTableHeader = () => {
    page.drawRectangle({ x: margin, y: y - 6, width: width - margin * 2, height: 22, color: rgb(0.965, 0.95, 0.92) });
    page.drawText('ITEM / IGICURUZWA', { x: col.desc + 6, y, size: 9, font: bold, color: NAVY });
    page.drawText('QTY', { x: col.qty, y, size: 9, font: bold, color: NAVY });
    page.drawText('PRICE', { x: col.price, y, size: 9, font: bold, color: NAVY });
    page.drawText('TOTAL', { x: col.total, y, size: 9, font: bold, color: NAVY });
    y -= 26;
  };
  const drawFooter = () => {
    page.drawLine({ start: { x: margin, y: 90 }, end: { x: width - margin, y: 90 }, thickness: 0.5, color: LINE });
    page.drawText('Murakoze gukorana natwe! / Thank you for your business.', { x: margin, y: 70, size: 10, font: bold, color: NAVY });
    page.drawText('Iyi ni inyemezabuguzi y\'ubucuruzi ikozwe na sisitemu - ntabwo ari EBM receipt yemewe na RRA.', { x: margin, y: 54, size: 7.5, font, color: MUTED });
    page.drawText('This is an internal business receipt generated by the app - not an official RRA-certified EBM receipt.', { x: margin, y: 44, size: 7.5, font, color: MUTED });
  };
  drawTableHeader();

  for (const r of rows) {
    const rowH = r.date ? 32 : 24;
    if (y - rowH < 200) { // need room for totals + footer -> continue on a new page
      drawFooter();
      page = doc.addPage([595.28, 841.89]);
      y = height - 70;
      drawTableHeader();
    }
    page.drawText(String(r.desc).slice(0, 42), { x: col.desc + 6, y, size: 10, font, color: rgb(0.15, 0.15, 0.15) });
    if (r.date) page.drawText(r.date, { x: col.desc + 6, y: y - 12, size: 7.5, font, color: MUTED });
    page.drawText(String(r.qty), { x: col.qty, y, size: 10, font, color: rgb(0.15, 0.15, 0.15) });
    page.drawText(fmtMoney(r.price), { x: col.price, y, size: 10, font, color: rgb(0.15, 0.15, 0.15) });
    page.drawText(fmtMoney(r.total), { x: col.total, y, size: 10, font: bold, color: rgb(0.15, 0.15, 0.15) });
    y -= rowH;
    page.drawLine({ start: { x: margin, y: y + 14 }, end: { x: width - margin, y: y + 14 }, thickness: 0.5, color: LINE });
  }

  y -= 10;
  // ---- Totals block ----
  const totalsX = 400;
  const drawTotalRow = (label, value, big) => {
    page.drawText(label, { x: totalsX, y, size: big ? 12 : 10, font: big ? bold : font, color: big ? NAVY : MUTED });
    const valStr = fmtMoney(value);
    page.drawText(valStr, { x: width - margin - (big ? bold : font).widthOfTextAtSize(valStr, big ? 12 : 10), y, size: big ? 12 : 10, font: big ? bold : font, color: big ? ACCENT : rgb(0.15, 0.15, 0.15) });
    y -= big ? 20 : 16;
  };
  drawTotalRow('Subtotal', totals.subtotal);
  drawTotalRow('TOTAL', totals.total, true);
  if (totals.amountPaid != null) drawTotalRow('Paid / Yishyuwe', totals.amountPaid);
  if (totals.balance != null && totals.balance < 0) {
    page.drawText('Balance / Ideni:', { x: 340, y, size: 10, font: bold, color: rgb(0.64, 0.23, 0.18) });
    const balStr = fmtMoney(Math.abs(totals.balance));
    page.drawText(balStr, { x: width - margin - bold.widthOfTextAtSize(balStr, 10), y, size: 10, font: bold, color: rgb(0.64, 0.23, 0.18) });
    y -= 16;
  }
  if (paymentMethod) {
    y -= 6;
    page.drawText(`Payment method / Uburyo bwo kwishyura: ${paymentMethod}`, { x: margin, y, size: 9.5, font, color: MUTED });
  }

  drawFooter();

  return doc.save();
}

router.get('/sale/:id', async (req, res) => {
  try {
    const businessId = businessIdOf(req.user);
    const data = db.read();
    const sale = data.sales.find(s => s.id === req.params.id && s.businessId === businessId);
    if (!sale) return res.status(404).json({ error: 'Igurisha ntiribonetse.' });
    const business = data.users.find(u => u.id === businessId) || {};
    const businessProfile = business.taxProfile || {};

    const payLabel = sale.paymentMethod === 'phone' ? 'Mobile Money' : sale.paymentMethod === 'bank' ? `Bank (${sale.bankName || ''})` : 'Cash';

    const bytes = await buildInvoicePdf({
      business, businessProfile,
      invoiceLabel: 'RECEIPT / FAGITIRE',
      invoiceNo: sale.invoiceNo || sale.id,
      date: sale.timestamp,
      customer: { name: sale.customerName, phone: sale.customerPhone, email: sale.customerEmail },
      rows: [{ desc: sale.productName, qty: sale.qty, price: sale.unitPrice, total: sale.total }],
      totals: { subtotal: sale.total, total: sale.total, amountPaid: sale.amountPaid, balance: sale.balance },
      paymentMethod: payLabel
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${sale.invoiceNo || 'invoice'}.pdf"`);
    res.send(Buffer.from(bytes));
  } catch (err) {
    console.error('Invoice generation error:', err);
    res.status(500).json({ error: "Habaye ikibazo mu gukora fagitire. Ongera ugerageze." });
  }
});

router.get('/customer', async (req, res) => {
  try {
    const customerName = (req.query.name || '').trim();
    if (!customerName) return res.status(400).json({ error: "Andika izina ry'umukiriya." });
    const businessId = businessIdOf(req.user);
    const data = db.read();
    const sales = data.sales
      .filter(s => s.businessId === businessId && (s.customerName || '') === customerName)
      .sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));
    if (sales.length === 0) return res.status(404).json({ error: 'Nta magurisha abonetse kuri uyu mukiriya.' });

    const business = data.users.find(u => u.id === businessId) || {};
    const businessProfile = business.taxProfile || {};
    const first = sales[0];

    const rows = sales.map(s => ({
      desc: s.productName, qty: s.qty, price: s.unitPrice, total: s.total,
      date: fmtD(s.timestamp)
    }));
    const subtotal = sales.reduce((sum, s) => sum + s.total, 0);
    const amountPaid = sales.reduce((sum, s) => sum + (s.amountPaid || 0), 0);

    const bytes = await buildInvoicePdf({
      business, businessProfile,
      invoiceLabel: 'STATEMENT / IFAGITIRE RUSANGE',
      invoiceNo: `STMT-${new Date().getFullYear()}-${customerName.slice(0, 3).toUpperCase()}`,
      date: new Date().toISOString(),
      customer: { name: first.customerName, phone: first.customerPhone, email: first.customerEmail },
      rows,
      totals: { subtotal, total: subtotal, amountPaid, balance: amountPaid - subtotal },
      paymentMethod: null
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="statement-${customerName.replace(/\s+/g, '_')}.pdf"`);
    res.send(Buffer.from(bytes));
  } catch (err) {
    console.error('Statement generation error:', err);
    res.status(500).json({ error: "Habaye ikibazo mu gukora fagitire. Ongera ugerageze." });
  }
});

module.exports = router;
